services:
  db:
    image: postgres:15
    container_name: project_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U app_user -d app_db']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
    ports:
      - '${BACKEND_PORT:-8080}:8080'

  chatbot:
    build: ./chatbot
    container_name: project_chatbot
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - '5005:5005'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
